User.create!([
  {email: "admin@test.com", encrypted_password: "$2a$12$70yhfgTeU4NhtgyjjsOKqOpFMAFmHwTyVf6rCbdiWeAVcdkMVoLva", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Admin", mobile_number: 123456789, gender: "Male", upload: nil, admin: true},
  {email: "bader@gmail.com", encrypted_password: "$2a$12$p88cnvHfGHbrhvgOoqyWAOi9en.5fqawbzgI2V.EQQXWNaBIMAfTu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "bader", mobile_number: 553396228, gender: "Male", upload: nil, admin: false},
  {email: "sara@gmail.com", encrypted_password: "$2a$12$Bh2RnNxm9SvScd1EmztkbutO0qwVXbIdSullAqh9uGAJaGLC0FsSe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Sara", mobile_number: 553396229, gender: "Female", upload: nil, admin: false},
  {email: "khalid@gmail.com", encrypted_password: "$2a$12$6.g9QLRsTYF9qRkX/VlTh.IBnQWRQfbbgQ.uMeJbKxFUjypaPirRC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Khalid", mobile_number: 553396228, gender: "Male", upload: nil, admin: false},
  {email: "ali@something.com", encrypted_password: "$2a$12$pQDPaKno2dVJQnrdCWhg6Omfuvlkc1hg5x8QaYfrX6hXtSWzAeTp6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Ali", mobile_number: 123456789, gender: "Male", upload: nil, admin: false},
  {email: "renad@gmail.com", encrypted_password: "$2a$12$FzAHY98X5xnTETgPg/Xu1.Ry99hyP3G5.TeKqKw66e9P5iPFY0Uza", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Renad", mobile_number: 999999999, gender: "Female", upload: nil, admin: false},
  {email: "hassan@gmail.com", encrypted_password: "$2a$12$AzoI4H4KPo9DtiWw/YXOKeiGlFdAookqcvrvChOS.gOumuYEO.7Xe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Hassan", mobile_number: 888888888, gender: "Male", upload: nil, admin: false},
  {email: "mazrou@gmail.com", encrypted_password: "$2a$12$.DK4XGn.8M0Rc7y3E.YTFeGr3bRcfdDsVwYhlSk6oYi1eEbKeCPfW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "Mazro", mobile_number: 666666666, gender: "Male", upload: nil, admin: false}
])
